version: 0.2

phases:
    build:
      commands:
        - echo Entered into build phase....
        - mvn clean package
    post_build:
      commands:
        - echo build completed successfully...

artifacts:
    files:
      - target/apiproductos.jar
    discard-paths: yes
